name: Cypress Tests

on:
  workflow_dispatch:  

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install dependencies
        run: |
          npm install

      - name: Run API Tests
        run: |
          npx cypress run --spec "cypress/tests/api/api.cy.js"

      - name: Run E2E Tests
        run: |
          npx cypress run --spec "cypress/tests/e2e/e2e.cy.js"
